// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC0qIjR1apvYJQeS-5r8VovStg3RsTwAY',
    appId: '1:612652045107:web:28131e82f53cbb6e3e6446',
    messagingSenderId: '612652045107',
    projectId: 'fir-curd-d2ef4',
    authDomain: 'fir-curd-d2ef4.firebaseapp.com',
    storageBucket: 'fir-curd-d2ef4.appspot.com',
    measurementId: 'G-T49BN15MP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGhgSiKQXYZhSTJVJha4qwOS73g-CwRN8',
    appId: '1:612652045107:android:1d85893a1973b11d3e6446',
    messagingSenderId: '612652045107',
    projectId: 'fir-curd-d2ef4',
    storageBucket: 'fir-curd-d2ef4.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC0qIjR1apvYJQeS-5r8VovStg3RsTwAY',
    appId: '1:612652045107:web:059fe2cc0bdff19c3e6446',
    messagingSenderId: '612652045107',
    projectId: 'fir-curd-d2ef4',
    authDomain: 'fir-curd-d2ef4.firebaseapp.com',
    storageBucket: 'fir-curd-d2ef4.appspot.com',
    measurementId: 'G-34JPR9FMVF',
  );
}
